---
title: "About Project"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


In July 2021, Georgia has launched the project on "Tracing the Link Between Climate Justice Action and the NDCs," which is already being implemented in Brazil, Columbia, Switzerland, Ukraine, and Germany. 

Since the International climate commitments are translated into national plans and strategies, resulting in local climate actions, the project's primary goal is to assess how well the NDC-ETF Framework allows for tracking local climate action in their respective capacities and capabilities and whether it helps or hinders energy access and climate just renewable energy systems. Thus, the case study will report on the following objectives: 

1. The traceability/translation of international climate commitments to national and local climate plans;
1. Authorities’ consistency in reporting on the implementation of 
local and national climate plans; 
1. Authorities report on the effects of the implementation of local 
and national climate action;
1. The traceability/recognition and contribution of the of 
community-based renewable energy projects.


This project is part of the [International Climate Initiative (IKI)](https://www.international-climate-initiative.com/en?iki_cookie_check=1).  [The Federal Ministry for the Environment, Nature Conservation and Nuclear Safety (BMU)](https://www.bmu.de/en/) supports this initiative on the basis of a decision adopted by the German Bundestag. The study is commissioned by [Bund für Umwelt und Naturschutz Deutschland e.V. (BUND)](https://www.bund.net/).